[package]
name = "file-processor"
version = "0.1.0"
description = "A file processor"
authors = ["you"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = ['custom-protocol'] }
tauri-plugin-shell = "2.0.0-beta"
tauri-plugin-dialog = "2.0.0-beta.9"
tauri-plugin-log = "2.0.0-beta.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tardis = { version = "0.1.0-rc.15", features = ["web-client", "fs"] }
